version: "3"
services:
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "2113:2113"
      - "1113:1113"
